### ISSUE TITLE
How to use it for boost Flowdroid

### ISSUE THREAD

**Issue by cjc-github** [JordanSamhi/JuCify#1]
Hi, How to use JuCify to boost the FlowDroid?I get the JuCify jar file.  but I don't know that how to achieve it for FlowDroid.Help！

**Comment by JordanSamhi** [comment]
Hi,

The Readme file explains how to install JuCify and how to use it.
You can also use the `-h` option to see the different options.

You can also have a loot at the different scripts that we provide in the `scripts` folder.

**Comment by cjc-github** [comment]
> Hi,
> 
> The Readme file explains how to install JuCify and how to use it. You can also use the `-h` option to see the different options.
> 
> You can also have a loot at the different scripts that we provide in the `scripts` folder.
Command 
java -jar JuCify-0.1-jar-with-dependencies.jar -a ../benchApps/getter_imei.apk -p /home/cao/Android/Sdk/platforms/ -ta

![image](https://user-images.githubusercontent.com/49013706/164592688-f00d41b1-8f6b-4d0c-9f0e-ed64b4ac6cf7.png)

**Comment by cjc-github** [comment]
How to get the result that running Flowdroid after applying JuCify?

**Comment by JordanSamhi** [comment]
The command you used does not use the results from the symbolic execution, that is why I said you should have a look at the scripts we provide. We rely on Angr for the symbolic execution, then the resulting files need to be loaded into JuCify. The scripts wrap everything. 
If you prefer doing it yourself you should execute Angr, get the resulting files and use the `-f` option to feed JuCify.

For instance:
`-a PATH_TO_APK -p PATH_TO_PLATFORMS -ta -f PATH/libnative-lib.so.callgraph:PATH/libnative-lib.so.result`

**Comment by JordanSamhi** [comment]
You can use the following command:
`./main.sh -f PATH_TO_APK -p PATH_TO_PLATFORMS`

**Comment by cjc-github** [comment]
Sorry, I thought the JuCify jar file ever embedded the symbol execution（angr）。

**Comment by cjc-github** [comment]
it shouldn't  need to uppack the apk.

I use the following command:
./main.sh -f ../benchApps/getter_imei.apk -p /home/cao/Android/Sdk/platforms/

Ls: inaccessible '.. /benchApps/getter_imei_result/': no file or directory

**Comment by cjc-github** [comment]
ok, I know. first, I should use angr to deal the so file ,then use JuCify to get the result

**Comment by JordanSamhi** [comment]
BTW, I just updated the README, I forgot to mention the `--recursive` option to clone JuCify since it has submodules and nativediscloser is not automatically fetched. Now it is the case. You can try.

**Comment by cjc-github** [comment]
nativediscloser doesn't work!

i use the following environment:
angr=8.20.7.6 (form the requirement.txt) python3.7.7

command:
python main.py ../benchApps/getter_imei.apk --out ../benchApps/getter_imei_result --cg

alought generated  getter_imei_reuslt directory,and the directory contains libnative-lib.so.map/dot/result file，but using these to perform script/main.py.
it's not working! 

![image](https://user-images.githubusercontent.com/49013706/164893566-280e1b7f-7e70-4346-842e-8e7e43273a70.png)

it seems to angr problem! I switch angr version to angr==9.2.1，but discloser project seems depends on the angr specific version.
![image](https://user-images.githubusercontent.com/49013706/164893798-ba8dbec1-d85f-48d3-b4ba-4742ae7d79d3.png)

**Comment by cjc-github** [comment]
it there something wrong with angr installation？

**Comment by JordanSamhi** [comment]
Did you checkout to commit 6897c58350773987da0a2c52a99fd4ebf1edc39e as I advised yesterday ?

**Comment by cjc-github** [comment]
yes, I first git checkout 6897c58 ,then mvn clean install.
Because the Jucify-0.1-jar-with-dependencies.jar depends on the pygraphviz.but PyGraphviz requires Python version 3.8 or later (3.7 detected).
so, I switch python version to 3.8.10，but generate the exception,it seems to soot problem?
![image](https://user-images.githubusercontent.com/49013706/164951687-53e13ba8-0048-471a-a8d5-fe49f9905cb9.png)

**Comment by cjc-github** [comment]
All commands are:

1、git clone https://github.com/JordanSamhi/JuCify.git
git clone https://github.com/gaojun0816/nativediscloser.git

2、git checkout 6897c58
mvn clean install

3、mkvirtualenv -p /usr/bin/python3.8 jucify_py38
cd nativediscloser
pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
python main.py --out ../benchApps/ --cg ../benchApps/getter_imei.apk

4、cd ../scripts/
pip install pygraphviz -i https://mirrors.aliyun.com/pypi/simple/
./main.sh -f ../benchApps/getter_imei.apk -p /home/cao/Android/Sdk/platforms/

**Comment by cjc-github** [comment]
Success

**Comment by JordanSamhi** [comment]
When cloning JuCify, use the --recursive option (I updated the README yesterday to add this) in order to get nativediscloser automatically.
Happy to see that you got it working.
Good luck for your work.

**Comment by cjc-github** [comment]
yes,when i perform git clone --recursive https://github.com/JordanSamhi/JuCify.git command. 

git@github.com: Permission denied (publickey).

Fatal: The remote repository cannot be read.

so,I git clone two times.

**Comment by cjc-github** [comment]
yes,I read the updated readme.md,Because my git lack of configure and too lazy to configure,so manual git clone two times.

**Comment by cjc-github** [comment]
thanks a lot. I will close the question.

**Comment by beyondgjc** [comment]
> nativediscloser doesn't work!
> 
> i use the following environment: angr=8.20.7.6 (form the requirement.txt) python3.7.7
> 
> command: python main.py ../benchApps/getter_imei.apk --out ../benchApps/getter_imei_result --cg
> 
> alought generated getter_imei_reuslt directory,and the directory contains libnative-lib.so.map/dot/result file，but using these to perform script/main.py. it's not working!
> 
> ![image](https://user-images.githubusercontent.com/49013706/164893566-280e1b7f-7e70-4346-842e-8e7e43273a70.png)


I met same problem, how to solve excuse me

**Comment by JordanSamhi** [comment]
Hi @beyondgjc ,

I am not sure to understand. You say that the result files are generated, then you say it does not work, could you clarify?

Also, as described in the README file, I highly encouraged you to use the scripts that are ready to use.

Thank you.

**Comment by beyondgjc** [comment]
Thank you for your reply. I encountered an error when using the script. 
![5ccf598c08a2642f5273f1aebf330c3](https://user-images.githubusercontent.com/37578705/168957610-a3a79267-580b-44a1-9534-74665f8dde25.jpg)
I looked at the closed problem and encountered the same problem when executing Python alone.

I see the code found unresolved reference 'mylib'  in the IDEA. I don't know if it matters.

I found I couldn't install pygraphviz, I'll fix it first.
Thanks!

**Comment by JordanSamhi** [comment]
Please check your Java version also, better use version 8 for soot-based programs like JuCify.

**Comment by beyondgjc** [comment]
Yes, I use java8. 
Seems to have some results, but seems to have some problems with python processing. Can you give me some suggestions?
![ddb0adf071ea1aa3e316434eb2fabbe](https://user-images.githubusercontent.com/37578705/168993405-8b3f84ff-68cd-47d6-bc72-d727f2a94198.jpg)

**Comment by beyondgjc** [comment]
I encounter an error when I run the command：python main.py --out ../benchApps/ --cg ../benchApps/getter_leaker.apk
`
DEBUG   | 2022-05-18 16:30:24,886 | ?[32m__main__?[0m | ?[32mUse shared library (i.e., .so) files from lib/armeabi-v7a/?[0m
DEBUG   | 2022-05-18 16:30:24,886 | ?[32m__main__?[0m | ?[32mStart to analyze lib/armeabi-v7a/libnative-lib.so?[0m
WARNING | 2022-05-18 16:30:28,053 | ?[31mcle.backends.externs?[0m | ?[31mSymbol was allocated without a known size; emulation may fail if it is used non-opaquely: __stack_chk_guard?[0m

WARNING | 2022-05-18 16:30:28,053 | ?[31mcle.backends.externs?[0m | ?[31mSymbol was allocated without a known size; emulation may fail if it is used non-opaquely: __sF?[0m
WARNING | 2022-05-18 16:30:28,053 | ?[36mcle.loader?[0m | ?[36mThe main binary is a position-independent executable. It is being loaded with a base address of 0x400000.?[0m
WARNING | 2022-05-18 16:30:28,053 | ?[36mcle.loader?[0m | ?[36mFor more information about "Symbol was allocated without a known size", see https://docs.angr.io/extending-angr/environme
nt#simdata?[0m
WARNING | 2022-05-18 16:30:28,061 | ?[34mangr.project?[0m | ?[34mAddress is already hooked, during hook(0x500014, <SimProcedure UnimplementedHook>). Not re-hooking.?[0m
WARNING | 2022-05-18 16:30:28,061 | ?[34mangr.project?[0m | ?[34mAddress is already hooked, during hook(0x500010, <SimProcedure UnimplementedHook>). Not re-hooking.?[0m
WARNING | 2022-05-18 16:30:28,061 | ?[34mangr.project?[0m | ?[34mAddress is already hooked, during hook(0x50002c, <SimProcedure UnimplementedHook>). Not re-hooking.?[0m
WARNING | 2022-05-18 16:30:28,061 | ?[34mangr.project?[0m | ?[34mAddress is already hooked, during hook(0x500038, <SimProcedure UnimplementedHook>). Not re-hooking.?[0m
WARNING | 2022-05-18 16:30:28,061 | ?[34mangr.project?[0m | ?[34mAddress is already hooked, during hook(0x500030, <SimProcedure UnimplementedHook>). Not re-hooking.?[0m
ERROR   | 2022-05-18 16:30:28,986 | ?[34mangr.analyses.cfg.cfg_fast?[0m | ?[34mDecoding error occurred at address 0x400a0a of function 0x400a0a.?[0m
ERROR   | 2022-05-18 16:30:28,986 | ?[34mangr.analyses.cfg.cfg_fast?[0m | ?[34mDecoding error occurred at address 0x400dce of function 0x400dce.?[0m
ERROR   | 2022-05-18 16:30:28,986 | ?[34mangr.analyses.cfg.cfg_fast?[0m | ?[34mDecoding error occurred at address 0x401006 of function 0x401006.?[0m
ERROR   | 2022-05-18 16:30:28,986 | ?[34mangr.analyses.cfg.cfg_fast?[0m | ?[34mDecoding error occurred at address 0x40182e of function 0x40182e.?[0m
ERROR   | 2022-05-18 16:30:28,991 | ?[34mangr.analyses.cfg.cfg_fast?[0m | ?[34mDecoding error occurred at address 0x4018d2 of function 0x4018d2.?[0m
?[31;1mDeprecation warning: Use self.model.get_any_node() instead of get_any_node?[0m
ERROR   | 2022-05-18 16:30:29,066 | ?[34mangr.analyses.cfg.cfg_fast?[0m | ?[34mDecoding error occurred at address 0x40086c of function 0x40086c.?[0m

WARNING | 2022-05-18 16:30:29,871 | ?[36mpyvex.lifting.gym.arm_spotter?[0m | ?[36mSpotting an LDM instruction at 0x40152c.  This is not fully tested.  Prepare for errors.?[0m
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\professional\anaconda3\envs\jucify_py38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\professional\anaconda3\envs\jucify_py38\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Traceback (most recent call last):
  File "main.py", line 429, in <module>
    main()
  File "main.py", line 100, in main
    cmd()
  File "main.py", line 169, in cmd
    apk_run(path_2_apk, out, output_cg)
  File "main.py", line 372, in apk_run
    p.start()
  File "D:\professional\anaconda3\envs\jucify_py38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\professional\anaconda3\envs\jucify_py38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\professional\anaconda3\envs\jucify_py38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\professional\anaconda3\envs\jucify_py38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\professional\anaconda3\envs\jucify_py38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
RecursionError: maximum recursion depth exceeded while pickling an object
`

**Comment by JordanSamhi** [comment]
Ok, it seems to work right? you can use the -t flag with script main.sh to perform taint analysis.

**Comment by beyondgjc** [comment]
Because the Python module did not execute successfully, only the Java module did.
"Has flow through native: No"

**Comment by JordanSamhi** [comment]
Oh you used the -t flag already, ok I see the problem. 
Since the python module did not execute successfully, the links between Java bytecode and native code were not computed.
I see you used python3.8 libs, if I remember correctly, you have to use python3.7 for this project.

**Comment by beyondgjc** [comment]
I switched to version 3.7.7, but it was still the same error

**Comment by JordanSamhi** [comment]
Can you send again the stack trace of the error message?

**Comment by beyondgjc** [comment]
![image](https://user-images.githubusercontent.com/37578705/169281583-c1f6b8b5-0839-490b-8f6c-7851f81c9b2a.png)
![image](https://user-images.githubusercontent.com/37578705/169281659-7c9129d0-8e9e-4345-ad12-96b6427137b2.png)

**Comment by JordanSamhi** [comment]
@gaojun0816 any idea ?

**Comment by gaojun0816** [comment]
The output looks really strange, it may re-hook some functions and cause some endless loops. @beyondgjc I believe you were analyzing our benchmark apps, right? If so I'm thinking it may be related to your OS. I notice that you are using Windows. I suggest you use a Linux VM to try again.

**Comment by beyondgjc** [comment]
Great, I switched to Linux and ran the results.
![image](https://user-images.githubusercontent.com/37578705/169551112-06ea1ba4-ab2c-4069-a4d3-10dd75de77ee.png)
Thank you for your help!

**Comment by JordanSamhi** [comment]
Perfect, thanks @gaojun0816.

**Comment by Dfault0** [comment]
> nativediscloser doesn't work!
> 
> i use the following environment: angr=8.20.7.6 (form the requirement.txt) python3.7.7
> 
> command: python main.py ../benchApps/getter_imei.apk --out ../benchApps/getter_imei_result --cg
> 
> alought generated getter_imei_reuslt directory,and the directory contains libnative-lib.so.map/dot/result file，but using these to perform script/main.py. it's not working!
> 
> ![image](https://user-images.githubusercontent.com/49013706/164893566-280e1b7f-7e70-4346-842e-8e7e43273a70.png)
> 
> it seems to angr problem! I switch angr version to angr==9.2.1，but nativediscloser project seems depends on the angr specific version. ![image](https://user-images.githubusercontent.com/49013706/164893798-ba8dbec1-d85f-48d3-b4ba-4742ae7d79d3.png)

@cjc-github i meet the same problem. how did you solve it?
my env is:
- python 3.7.7 or 3.8.10
- java 1.8.0
- ubuntu
- the nativediscloser  only can generate four files(libnative-lib.so.dot ，libnative-lib.so.result，libnative-lib.so.map  performance)
- no *.entrypoints file
- and the outputs of Jucify is:"Has flow through native: No"
